apiVersion: v1
kind: Service
metadata:
  name: misp-mysql
  namespace: misp
  labels:
    app: misp-mysql
    app.kubernetes.io/component: threat-intel-db
    app.kubernetes.io/part-of: xdr-platform
spec:
  type: ClusterIP
  selector:
    app: misp-mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
