apiVersion: v1
kind: Service
metadata:
  name: misp-redis
  namespace: misp
  labels:
    app: misp-redis
    app.kubernetes.io/component: threat-intel-cache
    app.kubernetes.io/part-of: xdr-platform
spec:
  type: ClusterIP
  selector:
    app: misp-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
