apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misp-files
  namespace: misp
  labels:
    app: misp-core
    app.kubernetes.io/part-of: xdr-platform
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: gp3-encrypted
  resources:
    requests:
      storage: 10Gi
