apiVersion: v1
kind: ConfigMap
metadata:
  name: zeek-config
  namespace: zeek
  labels:
    app: zeek
    app.kubernetes.io/part-of: xdr-platform
data:
  local.zeek: |
    @load base/frameworks/notice
    @load base/protocols/conn
    @load base/protocols/dns
    @load base/protocols/http
    @load base/protocols/ssl
    @load base/protocols/ssh
    @load policy/tuning/json-logs

    redef LogAscii::use_json = T;
