apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: hubble-relay-netpol
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      k8s-app: hubble-relay
  ingress:
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "4245"
              protocol: TCP
  egress:
    # Connect to Cilium agent on each node (observer port)
    - toEntities:
        - host
      toPorts:
        - ports:
            - port: "4244"
              protocol: TCP
