apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - coredns-netpol.yaml
  - hubble-relay-netpol.yaml
  - hubble-ui-netpol.yaml
  - external-secrets-netpol.yaml
  - cert-controller-netpol.yaml
  - falco-netpol.yaml
  - tetragon-operator-netpol.yaml
  - ebs-csi-netpol.yaml
  - efs-csi-netpol.yaml
  - alb-controller-netpol.yaml
  - cilium-health-netpol.yaml
